docs: fix some problems in docs/kitex/Tutorials/basic-feature/message_type
cloudwego/cloudwego.github.io pull request #1040
Opened 2024-03-16 09:27 UTC by zhu-mi-shan

#### What type of PR is this?

#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.
修复了docs/kitex/Tutorials/basic-feature/message_type文档的一些问题。

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en: 
The fixed problems include package reference problems, parameter problems, directory structure problems, parallel program problems...

zh(optional): 
修复的问题包含包引用问题、参数问题、目录结构问题、并行程序问题......

#### (Optional) Which issue(s) this PR fixes:

2024-03-16 09:54 UTC, cqqqq777 commented
语法上的错误可以修改，但是有些业务处理的的方式个人觉得没必要添加，此处应该只是展示各种消息类型的基本使用框架

2024-03-16 10:00 UTC, cqqqq777 requested changes

2024-03-16 10:00 UTC, cqqqq777 commented on content/en/docs/kitex/Tutorials/basic-feature/message_type.md
> +	"context"
导包的格式应该为：
import {
"标准库的包"
        .......

"项目内部导入的包"
       ......

"外部导入的包"
       ......
}

2024-03-16 10:00 UTC, cqqqq777 commented on content/zh/docs/kitex/Tutorials/basic-feature/message_type.md
> +	"github.com/cloudwego/kitex/client"
对齐问题

2024-03-16 10:00 UTC, cqqqq777 commented on content/zh/docs/kitex/Tutorials/basic-feature/message_type.md
> +	"context"
同上

2024-03-16 10:00 UTC, cqqqq777 commented on content/zh/docs/kitex/Tutorials/basic-feature/message_type.md
> +	"time"
同上

2024-03-16 10:00 UTC, cqqqq777 commented on content/zh/docs/kitex/Tutorials/basic-feature/message_type.md
> +	}
同上

2024-03-16 10:00 UTC, cqqqq777 commented on content/zh/docs/kitex/Tutorials/basic-feature/message_type.md
> +	"time"
同上

2024-03-16 10:00 UTC, cqqqq777 commented on content/zh/docs/kitex/Tutorials/basic-feature/message_type.md
> +	"time"
同

2024-03-16 10:00 UTC, cqqqq777 commented on content/zh/docs/kitex/Tutorials/basic-feature/message_type.md
> +	"time"
同上

2024-03-17 09:13 UTC, zhu-mi-shan commented on content/en/docs/kitex/Tutorials/basic-feature/message_type.md
> +	"context"
感谢指正，已修改问题。

2024-03-17 09:13 UTC, zhu-mi-shan commented on content/zh/docs/kitex/Tutorials/basic-feature/message_type.md
> +	"github.com/cloudwego/kitex/client"
感谢指正，是空格和缩进的问题，已修改问题。

2024-03-17 09:13 UTC, zhu-mi-shan commented on content/zh/docs/kitex/Tutorials/basic-feature/message_type.md
> +	"context"
感谢指正，是空格和Tab缩进的问题，已修改问题。

2024-03-17 09:14 UTC, zhu-mi-shan commented on content/zh/docs/kitex/Tutorials/basic-feature/message_type.md
> +	"time"
感谢指正，是空格和Tab缩进的问题，已修改问题。

2024-03-17 09:14 UTC, zhu-mi-shan commented on content/zh/docs/kitex/Tutorials/basic-feature/message_type.md
> +	}
感谢指正，是空格和Tab缩进的问题，已修改问题。

2024-03-17 09:14 UTC, zhu-mi-shan commented on content/zh/docs/kitex/Tutorials/basic-feature/message_type.md
> +	"time"
感谢指正，是空格和Tab缩进的问题，已修改问题。

2024-03-17 09:14 UTC, zhu-mi-shan commented on content/zh/docs/kitex/Tutorials/basic-feature/message_type.md
> +	"time"
感谢指正，是空格和Tab缩进的问题，已修改问题。

2024-03-18 02:10 UTC, GuangmingLuo commented on content/en/docs/kitex/Tutorials/basic-feature/message_type.md
> +				log.Println("recived:", req.GetMsg())
"recived" should be "received".

2024-03-18 05:33 UTC, AsterDY approved these changes

2024-03-18 06:41 UTC, merged