feat: improve tracing.md and visit_directly.md
cloudwego/cloudwego.github.io pull request #166
Opened 2022-05-01 15:02 UTC by li-jin-gou

2022-05-04 08:20 UTC, GuangmingLuo approved these changes

2022-05-07 06:33 UTC, simon0-o approved these changes

2022-05-10 12:06 UTC, lsjbd requested changes

2022-05-10 12:06 UTC, lsjbd commented on content/en/docs/kitex/Tutorials/basic-feature/visit_directly.md
>  If you want to send the requet to downstream that address determined, you can choose visiting directly without service discovery.
requet => request

2022-05-10 12:06 UTC, lsjbd commented on content/en/docs/kitex/Tutorials/basic-feature/visit_directly.md
>  If you want to send the requet to downstream that address determined, you can choose visiting directly without service discovery.
And `the request` => `a request`

2022-05-12 03:12 UTC, li-jin-gou commented on content/en/docs/kitex/Tutorials/basic-feature/visit_directly.md
>  If you want to send the requet to downstream that address determined, you can choose visiting directly without service discovery.
done

2022-05-12 06:23 UTC, lsjbd approved these changes

2022-05-12 06:25 UTC, merged