docs: add sentinel docs
cloudwego/cloudwego.github.io pull request #372
Opened 2022-09-29 07:09 UTC by Skyenought

#### What type of PR is this?
docs

#### What this PR does / why we need it (en: English/zh: Chinese):

en: add sentinel docs
zh: 添加集成 sentinel 组件的相关文档 

#### Which issue(s) this PR fixes:

2022-09-29 07:22 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/service-governance/sentinel.md
> +<div id="server">服务端</div>
为什么不用 ###

2022-09-29 07:22 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/service-governance/sentinel.md
> +### WithServerResourceExtractor
+详细补充

2022-09-29 07:22 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/service-governance/sentinel.md
> +关于 sentinel-golang 的基本配置, 这里不做赘述, 详情可以访问[文档](https://sentinelguard.io/zh-cn/docs/golang/quick-start.html)
sentinel-golang 的基本配置参考[文档](https://sentinelguard.io/zh-cn/docs/golang/quick-start.html)

2022-09-29 07:24 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/service-governance/sentinel.md
> +	initSentinel()
示例代码用 default配置 就可以吧，配置具体放在下面讲

2022-09-29 07:28 UTC, li-jin-gou commented
refer to https://github.com/cloudwego/cloudwego.github.io/pull/363

2022-10-11 11:52 UTC, welkeyever commented on content/zh/docs/hertz/tutorials/service-governance/sentinel.md
> +`SentinelClientMiddleware` 返回一个 `client.Middleware`。
`SentinelClientMiddleware` -> `SentinelClientMiddleware()`？

2022-10-26 03:54 UTC, li-jin-gou requested changes

2022-10-26 03:54 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/service-governance/sentinel.md
> +
空行处理一下

2022-10-26 03:54 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/service-governance/sentinel.md
> +
+1

2022-10-26 03:54 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/service-governance/sentinel.md
> +- `error` 来进行自定义错误处理
166 和 167 如果是一句话的话合并一下吧

2022-10-26 03:56 UTC, GuangmingLuo commented on content/zh/docs/hertz/tutorials/service-governance/sentinel.md
> +`SentinelServerMiddleware()`返回 `app.HandlerFunc` 类型, 用于将 sentinel-golang 集成进入 hertz server
返回前面少了个空格

2022-10-26 05:18 UTC, li-jin-gou approved these changes

2022-10-26 06:14 UTC, GuangmingLuo approved these changes

2022-10-26 06:16 UTC, merged