[WIP] doc: improve service_discover doc
cloudwego/cloudwego.github.io pull request #389
Opened 2022-10-12 04:31 UTC by L2ncE

#### What type of PR is this?
docs

#### What this PR does / why we need it (en: English/zh: Chinese):

en: improve service_discover doc
zh: 完善服务发现文档

2022-10-12 04:35 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery.md
> +| :--------------------- | :----------------------------------------------------------- |
这里不需要介绍 nacos-client sdk 的配置

2022-10-12 06:02 UTC, L2ncE commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery.md
> +| :--------------------- | :----------------------------------------------------------- |
> 这里不需要介绍 nacos-client sdk 的配置

收到

2022-10-12 06:02 UTC, L2ncE commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery.md
> +目前在 Hertz 的开源版本支持的服务发现扩展都存放在 [registry](https://github.com/hertz-contrib/registry) 中，欢迎大家参与项目贡献与维护。
> * 可以尝试将注册中心扩展列举一下，而不是只有 Nacos
> * 对于注册中心中使用的三方SDK的配置可以不做介绍，软链到三方文档或者仓库地址就可以。
> * 其余可以参考 jwt 的 pr [docs: improve jwt doc #369](https://github.com/cloudwego/cloudwego.github.io/pull/369)

收到

2022-10-15 07:32 UTC, L2ncE commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery.md
> +目前在 Hertz 的开源版本支持的服务发现扩展都存放在 [registry](https://github.com/hertz-contrib/registry) 中，欢迎大家参与项目贡献与维护。
> * 可以将注册中心扩展列举一下，而不是只有 Nacos
> * 对于注册中心中使用的三方SDK的配置可以不做介绍，软链到三方文档或者仓库地址就可以。
> * 其余可以参考 jwt 的 pr [docs: improve jwt doc #369](https://github.com/cloudwego/cloudwego.github.io/pull/369)
> * 以及英文

done

2022-10-15 08:24 UTC, rogerogers requested changes

2022-10-15 08:24 UTC, rogerogers commented on content/en/docs/hertz/tutorials/service-governance/service_discovery.md
> +, [polaris](https://github.com/hertz-contrib/registry/tree/main/polaris), [servicecomb](https://github.com/hertz-contrib/registry/tree/main/servicecomb), [zookeeper](https://github.com/hertz-contrib/
这里做成列表会不会好点。

2022-10-15 08:32 UTC, L2ncE commented on content/en/docs/hertz/tutorials/service-governance/service_discovery.md
> +, [polaris](https://github.com/hertz-contrib/registry/tree/main/polaris), [servicecomb](https://github.com/hertz-contrib/registry/tree/main/servicecomb), [zookeeper](https://github.com/hertz-contrib/
> 这里做成列表会不会好点。

done

2022-10-18 12:21 UTC, GuangmingLuo commented
标题typo：service_discovey

2022-10-18 12:22 UTC, L2ncE commented
> 标题typo：service_discovery

i got it, thx.

2022-10-18 12:46 UTC, L2ncE commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery.md
> +`NewDefaultNacosRegistry` 使用 nacos 创建一个默认的服务注册中心。会调用 `NewDefaultNacosConfig` 使用默认的客户端，设置 RegionID 为默认的 `cn-hangzhou` 且不会在开始时加载缓存。可自定义服务注册中心配置。
I got it, thx

2022-10-18 12:49 UTC, li-jin-gou requested changes

2022-10-18 12:49 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery.md
> +func main() {
文档中的代码也是需要 formart，这里需要检查一下

2022-10-23 14:02 UTC, L2ncE commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery.md
> +`NewDefaultNacosRegistry` 使用 nacos 创建一个默认的服务注册中心。会调用 `NewDefaultNacosConfig` 使用默认的客户端，设置 RegionID 为默认的 `cn-hangzhou` 且不会在开始时加载缓存。可自定义服务注册中心配置。
> 我认为这里需要描述一下使用这种初始化方式时所需要设置的默认值如
> 
> * https://github.com/hertz-contrib/registry/tree/main/nacos#environment-variable

done

2022-10-23 14:02 UTC, L2ncE commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery.md
>  ### 服务注册
> 我注意到 nacos 的扩展提供了 option 配置，这里需要描述一下

done

2022-10-23 14:02 UTC, L2ncE commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery.md
> +### 服务发现
> 服务发现同上

done

2022-10-23 14:02 UTC, L2ncE commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery.md
> +### 配置
> 这里的配置需要描述清楚是什么的配置

done

2022-10-23 14:02 UTC, L2ncE commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery.md
> +func main() {
> 文档中的代码也是需要 formart，这里需要检查一下

done

2022-10-24 05:11 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery.md
> +| cluster | nacos 的集群配置。                      |
这个配置似乎叫 `cluster` 不合适，因为对外的表示形式是 `WithCluster`, 可以看下 keyauth

2022-10-24 13:17 UTC, L2ncE commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery.md
> +| cluster | nacos 的集群配置。                      |
> 这个配置似乎叫 `cluster` 不合适，因为对外的表示形式是 `WithCluster`, 可以看下 keyauth 的 pr

done

2022-11-02 01:09 UTC, L2ncE commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery.md
> +到现在为止，支持的服务发现拓展有
> 第8行称为“扩展”，这里称为“拓展”，统一一下。

done

2022-11-02 01:09 UTC, L2ncE commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery.md
> +	// ...
> 示例代码部分缩进显示有些问题，尝试用 shift + tab 刷一下。

done

2022-11-08 15:34 UTC, li-jin-gou approved these changes

2022-11-09 02:33 UTC, merged