docs: update gzip docs
cloudwego/cloudwego.github.io pull request #404
Opened 2022-10-25 09:46 UTC by YUandJIANG

#### What type of PR is this?

docs
#### What this PR does / why we need it (en: English/zh: Chinese):

en:  update gzip docs
zh: 更新 gzip 文档

#### Which issue(s) this PR fixes:

2022-11-09 02:52 UTC, L2ncE commented on content/zh/docs/hertz/tutorials/basic-feature/middleware/gzip.md
> +示例代码如下：
“示例代码”和“示例代码如下”建议统一一下

2022-11-15 04:25 UTC, YUandJIANG commented on content/zh/docs/hertz/tutorials/basic-feature/middleware/gzip.md
> +示例代码如下：
GET

2022-11-16 13:36 UTC, li-jin-gou commented
@L2ncE  @justlorain PTAL

2022-11-16 14:21 UTC, justlorain commented on content/en/docs/hertz/tutorials/basic-feature/middleware/gzip.md
> +## Installation
“Installation” -> "Install"

2022-11-16 14:22 UTC, justlorain commented on content/en/docs/hertz/tutorials/basic-feature/middleware/gzip.md
> +## Sample Code:
remove colon

2022-11-16 14:28 UTC, justlorain commented on content/en/docs/hertz/tutorials/basic-feature/middleware/gzip.md
> +## Configuration
"Configuration" -> "Config"

2022-11-16 14:33 UTC, L2ncE requested changes

2022-11-16 14:33 UTC, L2ncE commented on content/en/docs/hertz/tutorials/basic-feature/middleware/gzip.md
> +
这里没有 Function Signature

2022-11-16 14:33 UTC, L2ncE commented on content/en/docs/hertz/tutorials/basic-feature/middleware/gzip.md
> +
这里空行太多了，删一下

2022-11-16 14:33 UTC, L2ncE commented on content/en/docs/hertz/tutorials/basic-feature/middleware/gzip.md
> +Function Signature
中文部分是 “函数签名如下：” 中英文统一都加冒号会不会好一点

其他部分也是一样

2022-11-17 05:30 UTC, YUandJIANG commented on content/en/docs/hertz/tutorials/basic-feature/middleware/gzip.md
> +## Installation
GET

2022-11-17 05:30 UTC, YUandJIANG commented on content/en/docs/hertz/tutorials/basic-feature/middleware/gzip.md
> +## Sample Code:
GET

2022-11-17 05:30 UTC, YUandJIANG commented on content/en/docs/hertz/tutorials/basic-feature/middleware/gzip.md
> +## Configuration
GET

2022-11-17 05:30 UTC, YUandJIANG commented on content/en/docs/hertz/tutorials/basic-feature/middleware/gzip.md
> +
GET

2022-11-17 05:30 UTC, YUandJIANG commented on content/en/docs/hertz/tutorials/basic-feature/middleware/gzip.md
> +Function Signature
GET

2022-11-17 15:17 UTC, li-jin-gou approved these changes

2022-11-21 03:37 UTC, merged