doc: add http2 docs
cloudwego/cloudwego.github.io pull request #466
Opened 2022-12-10 08:16 UTC by Claude-Zq

#### What type of PR is this?
docs
#### What this PR does / why we need it (en: English/zh: Chinese):
en: Add documentation for HTTP2
zh: 添加了HTTP2的文档

#### Which issue(s) this PR fixes:
Fixes https://github.com/cloudwego/hertz/issues/465

2022-12-10 09:06 UTC, Duslia commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +HTTP2是HTTP协议的第二个版本，旨在通过改进第一个HTTP版本的许多缺点，使应用程序更快、更简单、更健壮。
HTTP2 isn't the second version of HTTP

2022-12-10 09:09 UTC, Duslia commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +
Cloud you add the config doc of HTTP2? The server and client config is in https://github.com/hertz-contrib/http2/tree/main/config

2022-12-10 09:11 UTC, Duslia commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +用法示例：
You can emphasize that it it the h2c example.

2022-12-10 09:12 UTC, li-jin-gou requested changes
Please refer to https://github.com/cloudwego/cloudwego.github.io/pull/441 to refine pr.

2022-12-12 08:39 UTC, Claude-Zq commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +HTTP2是HTTP协议的第二个版本，旨在通过改进第一个HTTP版本的许多缺点，使应用程序更快、更简单、更健壮。
Sorry for the reference to the [wrong article](https://www.upwork.com/resources/what-is-http2)

2022-12-12 08:40 UTC, Claude-Zq commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +Hertz 提供了 HTTP2 的支持，参考了 [net/http2](https://github.com/golang/net/tree/master/http2) 的实现。
got it

2022-12-12 08:53 UTC, Claude-Zq commented
> Please refer to #441 to refine pr.

Sorry,I referred to  [Websocket documentation](https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/protocol/websocket/) earlier (also in the **[Protocol](https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/protocol/)** directory),and didn't notice that the http2 configuration was more complex and needed to be written into the documentation.
🤣

2022-12-12 09:11 UTC, Duslia commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +
There is no need give an example for every config. Just like here: https://www.cloudwego.io/docs/hertz/reference/config/   . Add a table is enough

2022-12-12 09:12 UTC, Duslia commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +	keyPEM = `-----BEGIN RSA PRIVATE KEY-----
The specific key content can use `keyPEM = "your key PEM"` instead. There is no need to show a complete keyPEM

2022-12-12 13:56 UTC, Claude-Zq commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +该协议的重点是性能；具体而言，最终用户感知的延迟、网络和服务器资源的使用。一个主要目标是允许使用从浏览器到网站的单一连接。
I think we should best refer to the official [http2 introduction](https://http2.github.io/) written by the [IETF HTTP Working Group](https://httpwg.github.io/).

2022-12-12 14:05 UTC, Claude-Zq commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +	keyPEM = `-----BEGIN RSA PRIVATE KEY-----
done

2022-12-13 01:00 UTC, Duslia commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +| `AllowHTTP`                  | `false`               | 设置是否允许http。                                       |
Add: the h2c switch

2022-12-13 01:03 UTC, Duslia commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +|:-------------------|:--------|
You can add introduction for each config.

2022-12-13 01:04 UTC, Duslia commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +package main
Delete example code for each option. It is too complex.

2022-12-14 12:17 UTC, Claude-Zq commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +| `AllowHTTP`                  | `false`               | 设置是否允许http。                                       |
done

2022-12-14 12:17 UTC, Claude-Zq commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +|:-------------------|:--------|
done

2022-12-14 12:21 UTC, Claude-Zq commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +package main
done and I have tried to show all the options in one example

2022-12-14 12:24 UTC, Duslia approved these changes

2022-12-14 12:27 UTC, li-jin-gou commented
PATl @L2ncE @justlorain @BaiZe1998

2022-12-14 13:38 UTC, BaiZe1998 commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +该协议的重点是性能；具体而言，最终用户感知的延迟、网络和服务器资源的使用。一个主要目标是允许使用从浏览器到网站的单一连接。
"该协议的重点是性能；具体而言，最终用户感知的延迟、网络和服务器资源的使用..." => "该协议的侧重点是性能：缩短用户感知的延迟、减少网络和服务器资源的使用..."

2022-12-14 13:38 UTC, BaiZe1998 commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +
The sample code seems to require formatting.

2022-12-14 14:40 UTC, justlorain commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +HTTP/2是对HTTP "在线" 表达方式的一种替代。它并不是对协议的彻底重写；HTTP方法、状态码和语义都是一样的，而且应该可以使用与HTTP/1.x相同的API（可能会有一些小的补充）来表示协议。
Add a space between Chinese and English

2022-12-14 14:40 UTC, justlorain commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +
remove unnecessary blank lines

2022-12-14 14:40 UTC, justlorain commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +用于设置是否禁用 `keep-alive`，默任不禁用。
"默任" -> "默认"

2022-12-14 14:40 UTC, justlorain commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +与http2规范不同，这里的`0`表示使用默认限制（目前是10MB）。如果想表示无限，可以设置为一个尽可能大的值（`0xffffffff` 或 `1<<32-1`）。
http2 -> HTTP2

2022-12-14 14:40 UTC, justlorain commented on content/en/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +	"github.com/cloudwego/hertz/pkg/app/client/retry"
import style

2022-12-14 14:40 UTC, justlorain commented on content/en/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +Sets the timeout for `Ping` responses, after which the connection will be closed if no response is received to `Ping `.The default is `15s`.
Sets -> Set

2022-12-14 14:40 UTC, justlorain commented on content/en/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +Used to set whether to allow http. if enabled, the client will use h2c mode. Not enabled by default.
http -> HTTP

2022-12-15 04:23 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +用于设置是否禁用 `keep-alive`，默任不禁用。
😂

2022-12-15 11:43 UTC, Claude-Zq commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +
done

2022-12-15 11:43 UTC, Claude-Zq commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +该协议的重点是性能；具体而言，最终用户感知的延迟、网络和服务器资源的使用。一个主要目标是允许使用从浏览器到网站的单一连接。
done

2022-12-15 11:43 UTC, Claude-Zq commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +HTTP/2是对HTTP "在线" 表达方式的一种替代。它并不是对协议的彻底重写；HTTP方法、状态码和语义都是一样的，而且应该可以使用与HTTP/1.x相同的API（可能会有一些小的补充）来表示协议。
done

2022-12-15 11:43 UTC, Claude-Zq commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +
done

2022-12-15 11:43 UTC, Claude-Zq commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +用于设置是否禁用 `keep-alive`，默任不禁用。
done

2022-12-15 11:43 UTC, Claude-Zq commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +与http2规范不同，这里的`0`表示使用默认限制（目前是10MB）。如果想表示无限，可以设置为一个尽可能大的值（`0xffffffff` 或 `1<<32-1`）。
done

2022-12-15 11:43 UTC, Claude-Zq commented on content/en/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +	"github.com/cloudwego/hertz/pkg/app/client/retry"
done

2022-12-15 11:43 UTC, Claude-Zq commented on content/en/docs/hertz/tutorials/basic-feature/protocol/http2.md
> +Used to set whether to allow http. if enabled, the client will use h2c mode. Not enabled by default.
done

2022-12-15 13:56 UTC, Duslia approved these changes

2022-12-15 14:09 UTC, merged

2022-12-15 14:09 UTC, li-jin-gou commented
LGTM