docs: add context doc
cloudwego/cloudwego.github.io pull request #619
Opened 2023-04-20 09:53 UTC by a631807682

#### What type of PR is this?

docs

#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.
- [ ] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io)

#### (Optional) Translate the PR title into Chinese.
添加上下文文档

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en: add context doc
zh: 添加上下文文档
基于 https://github.com/cloudwego/cloudwego.github.io/pull/450 上添加的上下文文档 @li-jin-gou 

#### (Optional) Which issue(s) this PR fixes:

#### (optional) The PR that updates user documentation:

2023-04-20 10:01 UTC, li-jin-gou commented
thanks

2023-04-28 06:31 UTC, welkeyever commented on content/zh/docs/hertz/tutorials/basic-feature/context/_index.md
> +title: "context"
标题叫`请求上下文`吧

2023-04-28 07:12 UTC, a631807682 commented on content/zh/docs/hertz/tutorials/basic-feature/context/_index.md
> +title: "context"
done

2023-04-28 08:53 UTC, rogerogers commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +- 从 [QueryArgs](#queryargs) 中获取值。
有序的可以用有序列表 :dog:

2023-04-28 08:53 UTC, rogerogers commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +### Reset
这个You should not use it，是不是可以不列出来了。

2023-04-28 09:25 UTC, a631807682 commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +### Reset
意思是不用写 `Reset` 这个 API 吗？其实我也不知道要不要列，因为写了"You should not use it"，但其实我们又支持`Copy`。

2023-04-28 09:27 UTC, a631807682 commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +设置 TraceInfo 。(更多内容请参考 [hertz-contrib/tracer](https://github.com/hertz-contrib/tracer))
改到了 hertz-contrib/obs-opentelemetry

2023-04-28 09:27 UTC, a631807682 commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +- 从 [QueryArgs](#queryargs) 中获取值。
done

2023-05-06 01:48 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +### Reset
我今天会CR&&能直接改的地方也会一同改掉，辛苦 @a631807682 ❤️

2023-05-10 06:08 UTC, a631807682 commented on content/zh/docs/hertz/tutorials/basic-feature/context/_index.md
> +weight: 3
done

2023-05-10 06:20 UTC, a631807682 commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +### Reset
改了下 reset 的描述

2023-06-14 03:31 UTC, GuangmingLuo commented
@a631807682 plz rebase and resolve conflicts, thanks

2023-06-14 03:41 UTC, a631807682 commented
> @a631807682 plz rebase and resolve conflicts, thanks

done

2023-06-14 08:14 UTC, GuangmingLuo commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +weight: 3
这个 weight 应该是1， response 的 weight 是 2

2023-06-14 08:14 UTC, GuangmingLuo commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +```
代码前后的空行是不是多余的

2023-06-14 08:32 UTC, a631807682 commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +weight: 3
done

2023-06-14 08:32 UTC, a631807682 commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +```
done

2023-07-02 03:14 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/context/response.md
> +```
是否需要添加说明：bodySize<0时数据全部写入，>=0时根据设置的bodySize大小写入数据

2023-07-02 06:54 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +
可以说明下FullPath函数和Path函数输出路径的区别

2023-07-02 07:36 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +获取路由 `Query String` 参数对象
加句号

2023-07-02 07:36 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +Args 对象提供了以下方法获取/设置 Query String 参数
加句号

2023-07-02 08:55 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +|`func (a *Args) ParseBytes(b []byte)` |解析 Query String|
可以改为解析字节数组b并将键值对存入QueryArgs对象

2023-07-02 09:01 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +| `func (u *URI) String() string`|获取完整 URI <http://example.com/user?baz=123> |
可以改为获取完整 URI 比如<http://example.com/user?baz=123>的完整URI是<http://example.com/user?baz=123>

2023-07-02 09:35 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +| `func (h *RequestHeader) SetMultipartFormBoundary(boundary string)`| 设置 Content-Type (Content-Type: multipart/form-data; boundary=----...) |
函数说明可以改为：当Content-Type=multipart/form-data时为其设置boundary

2023-07-02 09:41 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +| `func (h *RequestHeader) Get(key string) string`|获取键为 key 的值 |
函数说明中可以补充：Get函数是Peek函数的别名

2023-07-02 09:45 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +| `func (h *RequestHeader) GetAll(key string) []string`|获取键为 key 的所有值 |
函数说明中可以补充：GetAll函数是PeekAll函数的别名

2023-07-02 09:51 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +获取请求的 body 数据
加句号

2023-07-02 10:02 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +
可以考虑补充说明该函数支持从 application/x-www-form-urlencoded 和 multipart/form-data这两种类型的content-type中读取键值对

2023-07-03 05:09 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +| `func (h *RequestHeader) Get(key string) string`|获取键为 key 的值 |
这里描述不对

2023-07-03 05:09 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +| `func (h *RequestHeader) GetAll(key string) []string`|获取键为 key 的所有值 |
这里描述不对，不是别名的关系

2023-07-03 07:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cloudwego/cloudwego.github.io?pullRequest=619) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/cloudwego/cloudwego.github.io?pullRequest=619) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: li-jin-gou<br/>:white_check_mark: a631807682<br/>:white_check_mark: rogerogers<br/>:x: chaoranz758<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cloudwego/cloudwego.github.io?pullRequest=619) it.</sub>

2023-07-04 05:08 UTC, li-jin-gou requested changes

2023-07-04 05:08 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +### GetDuration
添加一个分类 “数据存储”，包含 Get** 和 Set

2023-07-04 05:08 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +### Bind
添加分类 参数绑定与校验

2023-07-04 05:08 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +### ClientIP
ClientIP 和 SetClientIPFunc 可以抽出来

2023-07-04 05:08 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +### Copy
添加分类 并发安全

2023-07-04 05:08 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +### Handler
添加分类 Handler 操作

2023-07-04 05:13 UTC, li-jin-gou requested changes

2023-07-04 05:13 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/context/response.md
> +设置 Status Code 并通过 Render 设置 ContentType 和 Body。(更多内容请参考 [server/render](https://github.com/cloudwego/hertz/tree/main/pkg/app/server/render))
(更多内容请参考 [server/render](https://github.com/cloudwego/hertz/tree/main/pkg/app/server/render)) 
感觉没必要跳回到代码里，可以跳到 rendor 的文档

2023-07-04 05:13 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/context/response.md
> +设置 Status Code 并通过 Render 设置 ContentType 和 Body。(更多内容请参考 [server/render](https://github.com/cloudwego/hertz/tree/main/pkg/app/server/render))
“更多内容请参考”  这个检查一下有没有有的内容已经有详细的文档了，有文档的话直接跳到文档吧。
有的是跳到代码示例，不如在代码示例里面把链接加好。
跳到源码的我理解可以干掉，加强文档描述。

2023-07-04 05:16 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/context/response.md
> +### XML
增加分类渲染，可以看下要不要直接说明跳到渲染的文档

2023-07-04 05:19 UTC, li-jin-gou requested changes

2023-07-04 05:19 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/context/response.md
> +### Render
context 的文档的一些API 和其它文档会有重复，保证一下描述一致，否则容易出现在两个文档描述不一致。

2023-07-04 05:23 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +func (ctx *RequestContext) IsPost() bool
IsGet 这几个方法并不是高频方法，可以把它删掉，将获取所有header、设置 header 放上来。

2023-07-04 05:26 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +### GetRawData
有点重复，这个看下可以删掉。

2023-07-04 05:26 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/context/request.md
> +### Body
FormValue  可以放到这来这个分类下。

2023-07-17 03:28 UTC, li-jin-gou commented
看了一下没什么问题了，辛苦 @a631807682 @GuangmingLuo @welkeyever @rogerogers  再看下，没什么问题的话打算合了。

2023-07-17 03:32 UTC, welkeyever approved these changes

2023-07-17 03:33 UTC, GuangmingLuo approved these changes

2023-07-17 03:35 UTC, li-jin-gou approved these changes

2023-07-17 03:35 UTC, li-jin-gou commented
LGTM

2023-07-17 03:35 UTC, merged

2023-07-17 09:04 UTC, welkeyever commented
@a631807682 @chaoranz758 High-quality output! Thank you very much for your contribution 🫡