doc(hertz): update service discovery doc
cloudwego/cloudwego.github.io pull request #623
Opened 2023-04-22 16:11 UTC by MulL1on

#### What type of PR is this?
doc

#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.
- [ ] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io)

#### (Optional) Translate the PR title into Chinese.
更新服务发现文档

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en: update the service discovery doc and correct some mistakes
zh(optional):  更新服务发现文档，并改正了一些问题

2023-04-24 04:00 UTC, li-jin-gou commented
thanks

2023-04-24 05:22 UTC, rogerogers requested changes

2023-04-24 05:22 UTC, rogerogers commented on content/en/docs/hertz/tutorials/service-governance/service_discovery/etcd.md
> +    r, err := etcd.NewEtcdRegistry([]string{"127.0.0.1:2379"},
r, err := etcd.NewEtcdResolver([]string{"127.0.0.1:2379"},

2023-04-24 05:53 UTC, rogerogers commented on content/en/docs/hertz/tutorials/service-governance/service_discovery/redis.md
> +     ))
这两个括号好像没用，代码有空格。

2023-04-24 05:53 UTC, rogerogers commented on content/en/docs/hertz/tutorials/service-governance/service_discovery/zookeeper.md
> +weight: 8
weight有重复

2023-04-24 05:55 UTC, rogerogers commented
貌似只有consul是newRegister其他都是newRegistry

2023-04-24 06:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cloudwego/cloudwego.github.io?pullRequest=623) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/cloudwego/cloudwego.github.io?pullRequest=623) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: MulL1on<br/>:x: root<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cloudwego/cloudwego.github.io?pullRequest=623) it.</sub>

2023-04-24 09:29 UTC, MulL1on commented on content/en/docs/hertz/tutorials/service-governance/service_discovery/etcd.md
> +    r, err := etcd.NewEtcdRegistry([]string{"127.0.0.1:2379"},
done

2023-04-24 09:29 UTC, MulL1on commented on content/en/docs/hertz/tutorials/service-governance/service_discovery/zookeeper.md
> +weight: 8
where?

2023-04-24 14:39 UTC, rogerogers commented on content/en/docs/hertz/tutorials/service-governance/service_discovery/zookeeper.md
> +weight: 8
看错了。

2023-05-04 11:48 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery/_index.md
> +此配置项可为客户端配置负载均衡算法和负载均衡参数。
说明一下默认的负载均衡实现是什么以及 option 的作用，然后再软链一下文档

2023-05-04 11:49 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery/_index.md
> +此配置项可为客户端配置负载均衡算法和负载均衡参数。
能用到 负载均衡的地方目前来看就是这里了

2023-05-04 11:50 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery/nacos.md
> +`NewDefaultNacosRegistry` 使用 nacos 创建一个默认的服务注册中心。会调用 `NewDefaultNacosConfig` 创建一个默认的 nacos 客户端， RegionId 为 `cn-hangzhou`、服务器地址为 `127.0.0.1`、服务器端口号为`8848`，且不会在启动时自动预加载服务实例信息到本地缓存。可自定义服务注册中心配置。
naocs 扩展比较特殊，这个方法是取的环境变量，可以看下代码调整一下描述

2023-05-04 11:57 UTC, li-jin-gou reviewed
英文的问题同上

2023-05-05 11:21 UTC, li-jin-gou commented
看了一下没啥问题了，大家可以再 review 一下 cc @GuangmingLuo @rogerogers @welkeyever

2023-05-05 11:21 UTC, li-jin-gou approved these changes

2023-05-05 11:25 UTC, welkeyever commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery/_index.md
> +| WithSD                 | 设置 isSD 为 true ，**使用服务发现必选**。 |
`isSD`是`RequestOptions`中的字段，这里没有提`RequestOptions`感觉有点突兀，可以先列一下`RequestOptions`重点字段，这个看起来应该是贯穿全文的一个重要结构

2023-05-05 11:49 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery/_index.md
> +| WithSD                 | 设置 isSD 为 true ，**使用服务发现必选**。 |
这里改一下描述吧，RequestOptions 放在这里不合适。

2023-05-05 11:58 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/service-governance/service_discovery/_index.md
> +| WithSD                 | 设置 isSD 为 true ，**使用服务发现必选**。 |
done

2023-05-05 12:25 UTC, welkeyever approved these changes

2023-05-05 13:49 UTC, merged