feat: silent mode
cloudwego/cloudwego.github.io pull request #632
Opened 2023-04-25 01:52 UTC by Duslia

#### What type of PR is this?

feat
#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.
- [ ] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io)

#### (Optional) Translate the PR title into Chinese.
安静模式

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en: add silentmode docs for Hertz
zh(optional): 增加安静模式文档

#### (Optional) Which issue(s) this PR fixes:

#### (optional) The PR that updates user documentation:

2023-04-25 02:58 UTC, GuangmingLuo commented on content/zh/docs/hertz/tutorials/observability/log.md
> +即可关闭这些日志
在初始化时添加如下配置，即可关闭这些日志。
--代码--

2023-05-07 15:53 UTC, li-jin-gou requested changes
加英文&&冲突需要解一下。

2023-05-08 03:24 UTC, li-jin-gou approved these changes

2023-05-08 03:24 UTC, li-jin-gou approved these changes

2023-05-08 03:36 UTC, merged