docs: add FAQ in docs of observability
cloudwego/cloudwego.github.io pull request #639
Opened 2023-05-12 07:28 UTC by ViolaPioggia

#### What type of PR is this?
docs

#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en: add FAQ in docs of observability
zh(optional): 丰富了可观测性的文档

2023-05-12 07:32 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/observability/log.md
> +在 https://github.com/hertz-contrib/obs-opentelemetry/tree/main/logging 有一个基于 hertz-contrib/logger 的 trace 实现。
不要链接到代码仓库了，链到文档吧 https://www.cloudwego.io/zh/docs/hertz/tutorials/observability/open-telemetry/#logging
描述略微调整一下&&注意中英文档的路径的不同

2023-05-12 07:57 UTC, ViolaPioggia commented on content/zh/docs/hertz/tutorials/observability/log.md
> +可以参照 https://www.cloudwego.io/zh/docs/hertz/tutorials/observability/open-telemetry/#logging 的 trace 实现文档
OK👍🏻

2023-05-14 07:49 UTC, li-jin-gou requested changes

2023-05-14 07:49 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/observability/log.md
> +You can refer to the logging section of the [Trace](https://www.cloudwego.io/docs/hertz/tutorials/observability/open-telemetry/) documentation.
https://www.cloudwego.io/docs/hertz/tutorials/observability/open-telemetry/#logging

2023-05-14 12:40 UTC, li-jin-gou approved these changes

2023-05-14 12:40 UTC, merged