docs: translate hertz/reference/migration
cloudwego/cloudwego.github.io pull request #643
Opened 2023-05-15 11:31 UTC by shiningstoned

2023-05-15 11:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cloudwego/cloudwego.github.io?pullRequest=643) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cloudwego/cloudwego.github.io?pullRequest=643) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cloudwego/cloudwego.github.io?pullRequest=643) it.</sub>

2023-05-16 03:43 UTC, li-jin-gou requested changes
补充一下 pr 的描述一下吧，参考一下其它 pr。

2023-05-16 04:23 UTC, li-jin-gou commented
看了一下没啥问题了，大家可以再 review 一下 cc @GuangmingLuo @rogerogers @welkeyever

2023-05-16 05:35 UTC, rogerogers commented on content/en/docs/hertz/tutorials/service-migration/migration.md
> +Other Migration Considerations:
这一句放在这里有点奇怪，要不标题层级调整下？这个二级，下面往下一级。

2023-05-16 05:35 UTC, rogerogers commented on content/en/docs/hertz/tutorials/service-migration/migration.md
> +  with detailed parameters referenced in the [server package - github.com/cloudwego/hertz/pkg/app/server - Go Packages](https://pkg.go.dev/github.com/cloudwego/hertz@v0.4.1/pkg/app/server#New).
这些链接到最新版本吧。

2023-05-16 05:57 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/service-migration/migration.md
> +  with detailed parameters referenced in the [server package - github.com/cloudwego/hertz/pkg/app/server - Go Packages](https://pkg.go.dev/github.com/cloudwego/hertz@v0.4.1/pkg/app/server#New).
done

2023-05-16 05:58 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/service-migration/migration.md
> +Other Migration Considerations:
把这行删掉了

2023-05-16 06:05 UTC, rogerogers approved these changes

2023-05-16 06:09 UTC, welkeyever commented on content/en/docs/hertz/tutorials/service-migration/_index.md
> +title: "API Service Migration to Hertz"
直接“Migration to Hertz” 吧

2023-05-16 06:10 UTC, welkeyever commented on content/zh/docs/hertz/tutorials/service-migration/_index.md
> +title: "API 服务迁移到 Hertz"
同“迁移到 Hertz”

2023-05-16 06:31 UTC, GuangmingLuo approved these changes

2023-05-16 06:34 UTC, li-jin-gou approved these changes

2023-05-16 06:34 UTC, li-jin-gou approved these changes

2023-05-16 06:34 UTC, merged