docs: add render docs
cloudwego/cloudwego.github.io pull request #662
Opened 2023-05-25 12:28 UTC by Hanser001

#### What type of PR is this?

docs

#### (Optional) Translate the PR title into Chinese.

增加render文档

2023-05-25 12:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cloudwego/cloudwego.github.io?pullRequest=662) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cloudwego/cloudwego.github.io?pullRequest=662) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cloudwego/cloudwego.github.io?pullRequest=662) it.</sub>

2023-05-26 02:18 UTC, GuangmingLuo commented
文档缺少 header 文件，参考其它文档补充下吧，注意 weight 设置

2023-05-29 03:13 UTC, rogerogers reviewed
中文的单词适当增加点空格吧，看起来更舒服点。

2023-05-29 03:13 UTC, rogerogers commented on content/zh/docs/hertz/tutorials/basic-feature/render.md
> +`Hertz`支持对JSON,HTML,Protobuf等的渲染。
```suggestion
`Hertz` 支持对 JSON, HTML, Protobuf 等的渲染。
```

2023-05-29 11:25 UTC, rogerogers commented on content/zh/docs/hertz/tutorials/basic-feature/render.md
> +`Hertz`支持对JSON,HTML,Protobuf等的渲染。
下面也还有其他地方这个样子。

2023-05-30 09:11 UTC, rogerogers reviewed
再看看，可能还有其他地方有，hertz这个单词本身不属于代码块

2023-05-30 09:11 UTC, rogerogers commented on content/zh/docs/hertz/tutorials/basic-feature/render.md
> +`Hertz` 支持对 JSON, HTML, Protobuf 等的渲染。
```suggestion
Hertz 支持对 JSON，HTML，Protobuf 等的渲染。
```

2023-05-30 09:11 UTC, rogerogers commented on content/zh/docs/hertz/tutorials/basic-feature/render.md
> +与 `JSON` 不同，`Data` 需要你自行设置Content-Type。此外 `Data` 只接收 **[]byte**。
```suggestion
与 `JSON` 不同，`Data` 需要你自行设置 `Content-Type`。此外 `Data` 只接收 **[]byte**。
```

2023-05-30 09:11 UTC, rogerogers commented on content/zh/docs/hertz/tutorials/basic-feature/render.md
> +Hertz支持渲染 `Protobuf`。
```suggestion
Hertz 支持渲染 `Protobuf`。
```

2023-05-30 11:41 UTC, Hanser001 commented
> 再看看，可能还有其他地方有，hertz这个单词本身不属于代码块

现在应该把Hertz这个词的部分都改好了，顺便找出了一个多余的空格

2023-05-31 06:31 UTC, rogerogers approved these changes

2023-05-31 07:35 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/basic-feature/render.md
> +weight: 10
这里的顺序影响文档的排序，重复了

2023-05-31 07:40 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/basic-feature/render.md
> +Hertz supports rendering of JSON, HTML, Protobuf, etc.
![image](https://github.com/cloudwego/cloudwego.github.io/assets/97824201/2dae523d-2fa9-4314-a879-1df33f0ff425)
Json 这里建议添加分类，用户经常会去寻找 IndentedJSON 合理的目录可以加速寻找，并且这里没有看到 IndentedJSON

2023-05-31 07:40 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/basic-feature/render.md
> +## HTML
缺少 Text 和 XML 的使用介绍

2023-05-31 07:42 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/basic-feature/render.md
> +## HTML
+ Data

2023-05-31 07:43 UTC, li-jin-gou commented
HTML 不需要介绍的这么详细，高频使用的 Json 和 protobuf 还有 Data 目前使用比较最多，基本看不到用 .HTML

2023-05-31 07:46 UTC, li-jin-gou requested changes
辛苦补全一下文档&优化一下目录结构

2023-06-01 03:31 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/basic-feature/render.md
> +weight: 10
@Hanser001 weight 参数还没修改

2023-06-01 05:22 UTC, li-jin-gou requested changes
缺少自定义 rendor 介绍

2023-06-08 03:36 UTC, li-jin-gou approved these changes

2023-06-08 03:36 UTC, merged

2023-06-08 03:37 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/render.md
> +package main
缺失的示例代码可以有时间补充道 hertz-example 中❤️

2023-06-09 03:55 UTC, Hanser001 commented on content/zh/docs/hertz/tutorials/basic-feature/render.md
> +package main
提交pr了🥰