docs: add client doc
cloudwego/cloudwego.github.io pull request #688
Opened 2023-06-27 10:54 UTC by Claude-Zq

#### What type of PR is this?
docs

#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en: Add Client documentation
zh(optional):  添加Client文档

#### (Optional) Which issue(s) this PR fixes:
none

2023-07-02 03:17 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/client.md
> +```
是否应该添加对重试配置函数配置项的具体说明&&是否考虑添加客户端的负载均衡部分的说明

2023-07-11 06:47 UTC, Claude-Zq commented on content/zh/docs/hertz/tutorials/basic-feature/client.md
> +```
got it

2023-07-12 12:36 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/client.md
> +title: "Client"
client可以考虑改为“客户端”

2023-07-12 12:53 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/client.md
> +| MaxConnWaitTimeout            | 0s             | 等待自由连接的最大时间。                                   |
等待空闲连接

2023-07-12 12:58 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/client.md
> +| DialFunc                      | network.Dialer | 自定义拨号器功能,会覆盖自定义拨号器                        |
中文逗号

2023-07-12 13:10 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/client.md
> +| DisablePathNormalizing        | nil            | 是否禁用路径规范化。                                       |
bool类型，应为false

2023-07-12 13:16 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/client.md
> +| DialTimeout                   | time.Second    | 拨号超时时间                                               |
改为1s

2023-07-12 13:19 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/client.md
> +| DialFunc                      | network.Dialer | 自定义拨号器功能,会覆盖自定义拨号器                        |
把描述中部分出现的句号去掉，统一规范

2023-07-12 13:23 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/client.md
> +```
示例代码可以更详细些（例如在print处给出打印的结果以表明函数的作用）

2023-07-12 13:25 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/client.md
> +`WithMaxIdleConnDuration` 函数用于设置空闲连接的最大持续时间。如果一条连接在空闲时间超过了设置的最大持续时间，它将被关闭。
“在”=》“的”

2023-07-12 13:25 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/client.md
> +`WithMaxConnDuration` 函数用于设置连接的最大持续时间。如果一条连接在持续时间超过了设置的最大持续时间，它将被关闭。
“在”=》“的”

2023-07-12 13:35 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/client.md
> +该函数不会跟随重定向。请使用 Ge t函数来跟随重定向。
Get

2023-07-12 13:41 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/client.md
> +Post 函数使用给定的 POST 参数向指定的 UR L发送 POST 请求。如果 dst 太小，则将被响应体替换并返回，否则将分配一个新的切片。该函数会自动跟随重定向。如果需要手动处理重定向，请使用 Do 函数。
UR L=》URL

2023-07-12 13:41 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/basic-feature/client.md
> +SetProxy 用来设置客户端代理的。
的去掉

2023-07-20 03:47 UTC, li-jin-gou requested changes

2023-07-20 03:47 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/basic-feature/client.md
> +## Config
配置有请求级别的配置和方法级别的配置，这里缺少方法级别的配置

2023-07-20 03:47 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/basic-feature/client.md
> +## Config
配置放在下面

2023-07-20 03:47 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/client.md
> +## SetRetryIfFunc
新增分类请求重试

2023-07-20 03:47 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/client.md
> +
加分类 TLS

2023-07-20 03:47 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/client.md
> +```
加分类服务发现

2023-07-20 03:47 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/basic-feature/client.md
> +## Do
新增分类 发送请求

2023-07-20 03:47 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/basic-feature/client.md
> +## DoTimeout
新增分类 请求超时

2023-07-20 03:47 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/basic-feature/client.md
> +`SetProxy` is used to set the client proxy.
新增分类正向代理

2023-07-20 03:47 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/basic-feature/client.md
> +
新增分类  关闭空闲连接

2023-07-20 03:47 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/basic-feature/client.md
> +
新增分类 上传文件

2023-07-20 03:47 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/basic-feature/client.md
> +```go
新增分类 流式

2023-07-20 03:47 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/basic-feature/client.md
> +### WithDialTimeout
这个示例代码太长多了，看看怎么优化？ 开个二级文档或者去掉完善表格吧

2023-07-20 03:47 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/basic-feature/client.md
> +Sample Code:
新增分类 添加请求内容
如何构造 Query 参数、www-url-encoded、multipart/form-data、json

2023-07-20 10:05 UTC, rogerogers commented on content/en/docs/hertz/tutorials/basic-feature/client.md
> +	status, body, _ := c.Get(context.Background(), nil, "https://www.example.com")
现在不支持https吧。

2023-07-20 13:12 UTC, chaoranz758 commented on content/en/docs/hertz/tutorials/basic-feature/client.md
> +	status, body, _ := c.Get(context.Background(), nil, "https://www.example.com")
我改一下

2023-07-23 13:43 UTC, li-jin-gou commented on content/en/docs/hertz/tutorials/basic-feature/client.md
> +## Config
客户端的配置分为 
- client 配置 在下面了
- 还有 request 配置 在这里 https://github.com/cloudwego/hertz/blob/develop/pkg/common/config/request_option.go，这个需要加一下

2023-07-24 02:23 UTC, GuangmingLuo commented on content/zh/docs/hertz/tutorials/basic-feature/client.md
> +weight: 3
时间和排序需要更新下，正常情况下新增文档排序在最后面（改动最小），如果排序靠前，其它文档的 weight 也需要跟着顺延调整

2023-07-26 06:35 UTC, welkeyever approved these changes
LGTM，thx~

2023-07-26 06:36 UTC, li-jin-gou approved these changes

2023-07-26 06:36 UTC, merged