docs: add document http3
cloudwego/cloudwego.github.io pull request #737
Opened 2023-07-29 13:35 UTC by chaoranz758

#### What type of PR is this?

docs

#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.

增加http3协议的文档

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en:docs: add document http3
zh(optional): docs: 增加http3协议的文档

#### (Optional) Which issue(s) this PR fixes:

2023-07-30 15:23 UTC, li-jin-gou requested changes

2023-07-30 15:23 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http3.md
> +HTTP3 基于 [quic-go](https://github.com/quic-go/quic-go) 实现，[实现链接](https://github.com/hertz-contrib/http3)。
参考 https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/protocol/http2/ 尝试进行完善，不是把 example 放上就可以了👀

2023-08-01 09:34 UTC, li-jin-gou commented
@chaoranz758  加英文

2023-08-01 13:23 UTC, li-jin-gou commented
PATL @welkeyever  @GuangmingLuo

2023-08-02 03:01 UTC, welkeyever commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http3.md
> +>注意：QUIC 协议依赖于 TLS 协议，因此需要提供 TLS配置。
“TLS配置”中间差了一个空格？

2023-08-02 03:03 UTC, GuangmingLuo commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http3.md
> +HTTP3 基于 [quic-go](https://github.com/quic-go/quic-go) 实现，[实现链接](https://github.com/hertz-contrib/http3)。
HTTP3 -> Hertz-HTTP3，和 123 行保持一致？

2023-08-02 03:23 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http3.md
> +>注意：QUIC 协议依赖于 TLS 协议，因此需要提供 TLS配置。
done

2023-08-02 03:23 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/basic-feature/protocol/http3.md
> +HTTP3 基于 [quic-go](https://github.com/quic-go/quic-go) 实现，[实现链接](https://github.com/hertz-contrib/http3)。
done

2023-08-02 03:23 UTC, li-jin-gou approved these changes

2023-08-02 03:24 UTC, merged