docs: update hz usage document
cloudwego/cloudwego.github.io pull request #787
Opened 2023-09-22 07:56 UTC by Skyenought

#### What type of PR is this?
docs

#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

zh(optional): 添加 hz update 的注意事项

#### (Optional) Which issue(s) this PR fixes:
https://github.com/cloudwego/hertz/issues/943

2023-09-23 13:00 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/toolkit/install.md
> +title: '安装'
不需要改变这里

2023-09-23 13:01 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/toolkit/usage-protobuf.md
> +  "使用 thrift 生成代码"
同不需要改变

2023-09-23 13:02 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/toolkit/usage.md
> +title: "基本使用"
标题不需要更改

2023-09-23 13:03 UTC, li-jin-gou commented on content/zh/docs/hertz/tutorials/toolkit/usage.md
> +在使用 `hz new` 创建了项目之后, 便可使用 IDL 文件编写项目接口, 便可以使用 `hz update` 系列的命令来更新项目代码.
这里读了很多遍，读不通顺

2023-09-23 13:03 UTC, li-jin-gou commented on content/zh/docs/hertz/getting-started/_index.md
> +假定我们已经完成了一次调用，需要对项目进行进一步的更新, 于是在项目根目录下新建一个 `hello.thrift`。
这里的描述也有问题

2023-09-23 13:05 UTC, li-jin-gou commented on content/zh/docs/hertz/getting-started/_index.md
> +假定我们已经完成了一次调用，需要对项目进行进一步的更新, 于是在项目根目录下新建一个 `hello.thrift`。
也不通顺

2023-09-23 13:07 UTC, li-jin-gou requested changes
标题不需要在这个PR中更改

2023-09-24 13:18 UTC, li-jin-gou commented on content/zh/docs/hertz/getting-started/_index.md
> +如果需要对项目进行进一步的更新, 应使用 `hz update` 命令, 这里以使用 idl 创建项的情况为例, 添加一个 `Bye` 方法。
这里以添加一个 `Bye` 方法为例。

2023-09-24 13:19 UTC, li-jin-gou commented on content/zh/docs/hertz/getting-started/_index.md
> +## 提示
删掉这部分吧

2023-09-28 04:40 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/toolkit/usage-thrift.md
> +
可以在最前面加上：与 protobuf 不同；IDL 后面缺少一个空格

2023-09-28 04:42 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/toolkit/usage.md
> +具体使用方法可参考[使用 protobuf](./usage-protobuf.md) 和 [使用 thrift](./usage-thrift.md)。
这块可以提醒下用户，hz 判断一个项目是否存在是看生成的 .hz 文件，若 .hz 文件存在使用 hz new 会报错，不存在使用 hz update 会报错

2023-09-28 04:42 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/toolkit/usage-protobuf.md
> +- 如果 IDL 的依赖和主 IDL 不在同一路径下，需要加入 `-I` 选项，其含义为 IDL 搜索路径，等同于 protoc 的 `-I` 命令。
如果主 IDL 的依赖和主 IDL 不在同一路径下

2023-09-28 04:43 UTC, chaoranz758 commented on content/zh/docs/hertz/tutorials/toolkit/usage-protobuf.md
> +  "hz 使用 (protobuf)。"
参考其他的文档这么写就行：description: "hz 使用 (protobuf)。"

2023-09-29 03:01 UTC, li-jin-gou approved these changes

2023-09-29 03:01 UTC, merged