docs: add document for idl_trimmer tool
cloudwego/cloudwego.github.io pull request #849
Opened 2023-11-08 06:41 UTC by tksky1

#### What type of PR is this?
docs

#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en: add document for thriftgo-idl-trimmer tool
zh(optional): 

#### (Optional) Which issue(s) this PR fixes:

2023-11-08 09:02 UTC, HeyJavaBean approved these changes

2023-11-08 09:02 UTC, HeyJavaBean commented on static/img/docs/idl_trimmer_process2.jpg
你图片有水印....

2023-11-08 09:02 UTC, HeyJavaBean commented on static/img/docs/idl_trimmer_process2.jpg
我ap点错了...忽略下....

2023-11-08 10:09 UTC, rogerogers requested changes
图片水印

2023-11-08 10:34 UTC, tksky1 commented on static/img/docs/idl_trimmer_process2.jpg
fixed

2023-11-09 02:11 UTC, GuangmingLuo commented on content/zh/docs/kitex/Tutorials/code-gen/idl_trimmer.md
> +## 简介
简介开头建议加一个 thrifgo 的简介和超链接。

2023-11-09 02:12 UTC, GuangmingLuo commented on content/zh/docs/kitex/Tutorials/code-gen/idl_trimmer.md
> +可以匹配除了EmployeeService.getEmployee外的所有方法。执行这条命令，可以单独从IDL中删除该方法及其依赖（且其他方法无依赖）的结构。
本文中英文间需要加一个空格，建议统一处理下

2023-11-09 02:13 UTC, GuangmingLuo commented on content/zh/docs/kitex/Tutorials/code-gen/idl_trimmer.md
> +为了方便通过 KiteX/Thriftgo 集成方法进行裁切时使用 trimmer tool 的参数配置，Thriftgo v0.3.3 版本（暂未发布，拉取最新commit即可）为 trimmer 工具提供了 yaml 配置文件支持。在集成 KiteX/Thriftgo 或直接使用 trimmer 工具时，trimmer 都会自动扫描并应用当前执行的目录（os.Getwd()）下的 trim_
KiteX -> Kitex 全文替换

2023-11-09 02:13 UTC, GuangmingLuo commented
补一个英文文档吧

2023-11-10 06:17 UTC, tksky1 commented
> 补一个英文文档吧

搞定了

2023-11-10 09:16 UTC, HeyJavaBean approved these changes

2023-11-10 09:16 UTC, GuangmingLuo approved these changes

2023-11-10 09:17 UTC, merged