docs:add config-center
cloudwego/cloudwego.github.io pull request #867
Opened 2023-11-29 13:14 UTC by ViolaPioggia

#### What type of PR is this?
docs
#### Check the PR title.
docs:add config-center

2023-11-30 04:38 UTC, li-jin-gou commented on content/en/docs/kitex/Tutorials/service-governance/config-center/_index.md
> +## Kitex provide configuration center
提供的信息比较少。首先应该说清楚这个功能的用途，然后提供了哪些扩展，如何自定义实现。

2023-12-03 05:01 UTC, li-jin-gou commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/etcd.md
> +`func (c *client) SetParser(parser ConfigParser)`
光看到了一堆方法的介绍

2023-12-03 05:03 UTC, li-jin-gou commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/etcd.md
> +## 安装
没讲 server 和 client 端怎么用

2023-12-03 05:05 UTC, li-jin-gou commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/etcd.md
> +| Address          | 127.0.0.1                                                   | Etcd 服务器地址
option 和 https://github.com/kitex-contrib/config-etcd/blob/main/etcd/etcd.go#L60 对不上

2023-12-03 05:52 UTC, XZ0730 commented on content/en/docs/kitex/Tutorials/service-governance/config-center/etcd.md
> +	etcdClient, err := etcd.NewClient(etcd.Options{})
比如etcdkeeper可视化的截图或者别的

2023-12-03 10:29 UTC, li-jin-gou commented on content/en/docs/kitex/Tutorials/service-governance/config-center/etcd.md
> +	etcdClient, err := etcd.NewClient(etcd.Options{})
图片不需要，把 option 列出来，列对就可以

2023-12-04 04:27 UTC, li-jin-gou requested changes

2023-12-04 08:54 UTC, li-jin-gou commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/_index.md
> +kitex-contrib 提供了对于社区主流配置中心的拓展，实现了动态配置对接 kitex 治理特性
检查标点符号

2023-12-04 08:55 UTC, li-jin-gou commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/_index.md
> +kitex-contrib 提供了对于社区主流配置中心的拓展，实现了动态配置对接 kitex 治理特性
英文也需要检查

2023-12-04 08:55 UTC, li-jin-gou commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/_index.md
> +Server 端和 Client 端都是通过 WithSuite 这个方法来启用新的套件。
注入新的套件

2023-12-04 09:04 UTC, li-jin-gou commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/etcd.md
> +```
缺少示例，导致不清楚这个 CustomFunction 和  Key的实际作用

2023-12-04 09:06 UTC, li-jin-gou commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/etcd.md
> +| ServerPathFormat | {{.ServerServiceName}}/{{.Category}}                        | 使用 go [template](https://pkg.go.dev/text/template) 语法渲染生成对应的 ID, 使用 `ServiceName` `Category` 两个元数据
使用 go [template](https://pkg.go.dev/text/template) 语法渲染生成对应的 ID, 使用 ServiceName Category 两个元数据

缺少实际的作用

2023-12-04 09:07 UTC, li-jin-gou commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/etcd.md
> +| ConfigParser     | defaultConfigParser                                         | 解析 json 数据的解析器
缺少实际的作用

2023-12-04 09:09 UTC, li-jin-gou commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/etcd.md
> +更多示例请参考 [example](https://github.com/kitex-contrib/config-etcd/tree/main/example)
去掉

2023-12-04 09:11 UTC, li-jin-gou commented on content/en/docs/kitex/Tutorials/service-governance/config-center/etcd.md
> +## SetParser
改完 ###

2023-12-05 06:06 UTC, li-jin-gou commented on content/en/docs/kitex/Tutorials/service-governance/config-center/_index.md
> +For more information about Suite, please see [Suite](../../framework-exten/suite.md)
连接 404 了

2023-12-05 06:29 UTC, li-jin-gou approved these changes

2023-12-05 06:51 UTC, merged