doc: add the document to introduce the config-nacos
cloudwego/cloudwego.github.io pull request #896
Opened 2023-12-14 13:17 UTC by whalecold

#### What type of PR is this?

doc
#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en:
zh(optional): 

#### (Optional) Which issue(s) this PR fixes:

2023-12-14 14:11 UTC, li-jin-gou commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/nacos.md
> +weight: 100
100 -> 3

2023-12-14 14:11 UTC, li-jin-gou commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/nacos.md
> +`go get github.com/kitex-contrib/config-nacos`
添加英文文档

2023-12-14 14:12 UTC, li-jin-gou commented
cc @cqqqq777  @ViolaPioggia

2023-12-14 14:34 UTC, whalecold commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/nacos.md
> +`go get github.com/kitex-contrib/config-nacos`
英文版没有对应的目录～

2023-12-14 14:39 UTC, ViolaPioggia requested changes

2023-12-14 14:39 UTC, ViolaPioggia commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/nacos.md
> +---
weight: 4

2023-12-14 14:39 UTC, ViolaPioggia commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/nacos.md
> +		new(EchoImpl),
"ServiceName" 后面也和  README 一样加个注释吧

2023-12-14 14:39 UTC, ViolaPioggia commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/nacos.md
> +[JSON Schema](https://github.com/cloudwego/kitex/blob/develop/pkg/limiter/item_limiter.go#L33)
为了对其 etcd 和 apollo 文档，Category=limit另外起一行吧

2023-12-14 14:39 UTC, ViolaPioggia commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/nacos.md
> +            },
"error_rate": 0.3

2023-12-14 14:39 UTC, ViolaPioggia commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/nacos.md
> +[JSON Schema](https://github.com/cloudwego/kitex/blob/develop/pkg/rpctimeout/item_rpc_timeout.go#L42)
Category=rpc_timeout 同理另起一行

2023-12-14 14:39 UTC, ViolaPioggia commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/nacos.md
> +
更多信息可以删除，在主页介绍过了

2023-12-14 14:39 UTC, ViolaPioggia commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/nacos.md
> +
`SetParser` 等方法可以参考 etcd 文档详细介绍一下，不然用户可能不太清楚到底有什么用

2023-12-14 16:07 UTC, cqqqq777 commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/nacos.md
> +`func NewSuite(service string, cli nacos.Client, opts ...utils.Option) *NacosServerSuite `
中间少了一个换行，渲染出来的是没有换行的

2023-12-14 16:07 UTC, cqqqq777 commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/nacos.md
> +`func NewSuite(service, client string, cli nacos.Client, opts ...utils.Option) *NacosClientSuite `
同上

2023-12-14 16:07 UTC, cqqqq777 commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/nacos.md
> +允许用户自定义 nacos 的参数.
这个末尾还是用中文句号吧

2023-12-15 03:05 UTC, li-jin-gou commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/nacos.md
> +`go get github.com/kitex-contrib/config-nacos`
weight 应该是 4 ，sry

2023-12-15 08:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cloudwego/cloudwego.github.io?pullRequest=896) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/cloudwego/cloudwego.github.io?pullRequest=896) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: whalecold<br/>:x: 郑力升<br/><hr/>**郑力升** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cloudwego/cloudwego.github.io?pullRequest=896) it.</sub>

2023-12-15 09:06 UTC, ViolaPioggia commented on content/en/docs/kitex/Tutorials/service-governance/config-center/nacos.md
> +
这里是不是可以删掉 ####

2023-12-15 09:07 UTC, ViolaPioggia commented on content/en/docs/kitex/Tutorials/service-governance/config-center/nacos.md
> +
这里加了 Note 的话，中文文档也加一下吧

2023-12-15 15:25 UTC, li-jin-gou approved these changes

2023-12-15 15:25 UTC, merged