doc: sync User guide to generic call with dynamicgo
cloudwego/cloudwego.github.io pull request #900
Opened 2023-12-17 07:45 UTC by alice-yyds

2023-12-17 17:22 UTC, cqqqq777 requested changes

2023-12-17 17:22 UTC, cqqqq777 commented on content/en/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +&emsp;&emsp;- `WithCustomDynamicgoConvOpts(opts conv.Options)`: customized dynamicgo conv options for json/http generic call
这里的无序列表没有生效，应该是前面两个空格的问题

2023-12-17 17:22 UTC, cqqqq777 commented on content/en/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +| <u>Fallback</u>**condition** | **Encoding**             | **Decoding** |
Fallback 和 condition 之间少了个空格
第二列的应该是 require 之类的吧
第三列差内容，看中文的应该是 option

2023-12-17 17:22 UTC, cqqqq777 commented on content/en/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +Type: JSON string
这里格式渲染出来很奇怪

2023-12-17 17:22 UTC, cqqqq777 commented on content/en/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +Type: JSON string
同上

2023-12-17 17:22 UTC, cqqqq777 commented on content/en/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +Type: *generic.HTTPResponse
同上并且多了个 *

2023-12-17 17:22 UTC, cqqqq777 commented on content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +&emsp;&emsp;- `WithCustomDynamicgoConvOpts(optsconv. Options）`：自定义的 json/超文本传输协议的 conv 选项
无序列表未生效

2023-12-17 17:22 UTC, cqqqq777 commented on content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +| http         | CPU 架构：amd64 && go>=1.16 | - `ProviderOption` 的 `DynamicGoEnable` 为 true - `UseRawBodyForHTTPResp(true）` **启用（可选）**                                       |
选项一列   在飞书文档中应该是无序列表但是这里不支持

2023-12-17 17:22 UTC, cqqqq777 commented on content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +类型：JSON 字符串
格式很奇怪

2023-12-17 17:22 UTC, cqqqq777 commented on content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +类型：JSON 字符串
同上

2023-12-17 17:22 UTC, cqqqq777 commented on content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +类型：*generic.HTTPResponse
同上且多了个 *

2023-12-18 00:14 UTC, ahaostudy commented on content/en/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +&emsp;&emsp;- `WithCustomDynamicgoConvOpts(opts conv.Options)`: customized dynamicgo conv options for json/http generic call
GitHub 的 markdown 不支持这种缩进（没有一级，直接使用第二级缩进），所以使用空格代替了

2023-12-18 00:28 UTC, ahaostudy commented on content/en/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +Type: *generic.HTTPResponse
这个好像是本来就有的？

2023-12-18 00:31 UTC, ahaostudy commented on content/en/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +Type: JSON string
好像与原格式是一致的

2023-12-18 00:34 UTC, ahaostudy commented on content/en/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +| <u>Fallback</u>**condition** | **Encoding**             | **Decoding** |
这个我看下

2023-12-18 00:37 UTC, ahaostudy commented on content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +| http         | CPU 架构：amd64 && go>=1.16 | - `ProviderOption` 的 `DynamicGoEnable` 为 true - `UseRawBodyForHTTPResp(true）` **启用（可选）**                                       |
这个也没办法，这不属于标准md支持的格式，不过不应观看应该问题不大

2023-12-18 05:10 UTC, cqqqq777 commented on content/en/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +Type: *generic.HTTPResponse
是的，sry

2023-12-27 08:45 UTC, GuangmingLuo commented on content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +description: "泛化调用接入 dynamicgo 指南"
这个 desciption 太简单了，可以丰富下

2023-12-27 08:45 UTC, GuangmingLuo commented on content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +用法与原始 kitex 泛化调用基本相同，但有以下区别。
Kitex 中 K 大写

2023-12-27 08:46 UTC, GuangmingLuo commented on content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +[https://github.com/cloudwego/kitex/blob/develop/pkg/generic/json_test/generic_test.go#L80](https://github.com/cloudwego/kitex/blob/develop/pkg/generic/json_test/generic_test.go#L80)
[示例代码](https://github.com/cloudwego/kitex/blob/develop/pkg/generic/json_test/generic_test.go#L80)

另外，文档里面可以提供简化版的示例代码

2023-12-27 08:47 UTC, GuangmingLuo commented on content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +[https://github.com/cloudwego/kitex/blob/develop/pkg/generic/http_test/generic_test.go#L96](https://github.com/cloudwego/kitex/blob/develop/pkg/generic/http_test/generic_test.go#L96)
同上

2023-12-27 08:47 UTC, GuangmingLuo commented on content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +Source code: [https://github.com/cloudwego/kitex-benchmark/pull/59](https://github.com/cloudwego/kitex-benchmark/pull/59)
同上，不要平铺链接

2023-12-27 09:14 UTC, AsterDY commented on content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-dynamicgo.md
> +[https://github.com/cloudwego/kitex/blob/develop/pkg/generic/json_test/generic_test.go#L80](https://github.com/cloudwego/kitex/blob/develop/pkg/generic/json_test/generic_test.go#L80)
这个后面让 @cqqqq777 加一下吧

2023-12-27 09:26 UTC, GuangmingLuo approved these changes

2023-12-27 09:26 UTC, merged