doc: add the document to introduce the config-zookeeper
cloudwego/cloudwego.github.io pull request #901
Opened 2023-12-18 16:27 UTC by jiuxia211

#### What type of PR is this?

doc

#### Check the PR title.

-  This PR title match the format: <type>(optional scope): <description>
-  The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en:
zh(optional):

#### (Optional) Which issue(s) this PR fixes:

2023-12-19 09:02 UTC, li-jin-gou commented
cc @ViolaPioggia  @cqqqq777

2023-12-19 09:04 UTC, li-jin-gou commented on content/en/docs/kitex/Tutorials/service-governance/config-center/zookeeper.md
> +title: "zookeeper"
https://www.cloudwego.io/zh/docs/kitex/tutorials/service-governance/config-center/ 这里也需要补充一下 
![image](https://github.com/cloudwego/cloudwego.github.io/assets/97824201/342d1d17-4eb0-4eb0-a732-9d53a16b85c9)

2023-12-19 09:05 UTC, ViolaPioggia commented on content/en/docs/kitex/Tutorials/service-governance/config-center/zookeeper.md
> +		client.WithSuite(zookeeperclient.NewSuite(serviceName, clientName, zookeeperClient, &cl)),
这里中文替换成英文

2023-12-19 09:11 UTC, cqqqq777 requested changes

2023-12-19 09:11 UTC, cqqqq777 commented on content/en/docs/kitex/Tutorials/service-governance/config-center/zookeeper.md
> +`func (c *client) SetParser(parser ConfigParser)`
中间少了一个换行

2023-12-19 09:11 UTC, cqqqq777 commented on content/en/docs/kitex/Tutorials/service-governance/config-center/zookeeper.md
> +| 参数             | 变量默认值                                                  | 作用                                                         |
表格也要用英文

2023-12-19 09:11 UTC, cqqqq777 commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/zookeeper.md
> +kitex-contrib/config-zookeeper 中的最终path由ConfigParam中的Prefix和Path拼接而成：`param.Prefix + "/" + param.Path`
中英文之间要有空格

2023-12-19 09:12 UTC, ViolaPioggia commented on content/en/docs/kitex/Tutorials/service-governance/config-center/zookeeper.md
> +###
最后这里如果没有其他内容就把 `###` 去掉吧

2023-12-19 15:40 UTC, XZ0730 commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/zookeeper.md
> +	return sonic.Unmarshal([]byte(data), config)
如果支持yaml或者其他文件类型，为了体现自定义，例子建议使用yaml或者其他解析方式

2023-12-22 05:00 UTC, li-jin-gou commented on content/en/docs/kitex/Tutorials/service-governance/config-center/zookeeper.md
> +weight: 5
weight 调整为 6 吧

2023-12-23 05:22 UTC, jiuxia211 commented
提到了问题都fixed了，抱歉拖了有点久

2023-12-23 12:15 UTC, li-jin-gou approved these changes

2023-12-23 12:15 UTC, merged