add the document to introduce the config-file
cloudwego/cloudwego.github.io pull request #904
Opened 2023-12-20 18:35 UTC by ozline

#### What type of PR is this?

doc

#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en:
zh(optional): 

#### (Optional) Which issue(s) this PR fixes:

2023-12-21 01:11 UTC, li-jin-gou commented on content/en/docs/kitex/Tutorials/service-governance/config-center/file.md
> +weight: 2
weight 调整一下到 5

2023-12-21 01:12 UTC, li-jin-gou commented
cc @ViolaPioggia @cqqqq777

2023-12-21 02:56 UTC, XZ0730 commented on content/en/docs/kitex/Tutorials/service-governance/config-center/file.md
> +Example:
建议在每个服务治理配置json之前单独说明一下key是什么

2023-12-21 02:56 UTC, XZ0730 commented on content/en/docs/kitex/Tutorials/service-governance/config-center/file.md
> +
配置说明，key说明

2023-12-21 02:56 UTC, XZ0730 commented on content/en/docs/kitex/Tutorials/service-governance/config-center/file.md
> +
filepath，key等

2023-12-21 03:09 UTC, li-jin-gou commented on content/en/docs/kitex/Tutorials/service-governance/config-center/file.md
> +Example:
such as 
![image](https://github.com/cloudwego/cloudwego.github.io/assets/97824201/ed107906-c687-4e82-b96a-25b900cbe2fa)

2023-12-21 07:57 UTC, cqqqq777 requested changes

2023-12-21 07:57 UTC, cqqqq777 commented on content/en/docs/kitex/Tutorials/service-governance/config-center/file.md
> +
这里的换行可以去了

2023-12-21 07:57 UTC, cqqqq777 commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/file.md
> +weight: 2
中文的 weight 也要改

2023-12-22 00:22 UTC, ozline commented on content/zh/docs/kitex/Tutorials/service-governance/config-center/file.md
> +weight: 2
Done

2023-12-22 00:22 UTC, ozline commented on content/en/docs/kitex/Tutorials/service-governance/config-center/file.md
> +
Done

2023-12-22 00:29 UTC, ozline commented on content/en/docs/kitex/Tutorials/service-governance/config-center/file.md
> +Example:
在编写提案的时候期望是多服务复用单配置文件，这里已经做了修改，但是会和其他几个方案有出入

2023-12-22 00:41 UTC, ozline commented on content/en/docs/kitex/Tutorials/service-governance/config-center/file.md
> +
其他的仓库允许perfix留空，在 config-file 中是不允许的，这涉及到文件监听的系统细节，我们需要保证文件真实存在，否则监听不会生效。因此这里并不需要传统意义上的 configpath/filepath，key 也不会和 filepath 挂钩。

2023-12-22 00:47 UTC, ozline commented on content/en/docs/kitex/Tutorials/service-governance/config-center/file.md
> +weight: 2
Done

2023-12-22 04:43 UTC, li-jin-gou commented on content/en/docs/kitex/Tutorials/service-governance/config-center/file.md
> +Example:
GET

2023-12-22 04:59 UTC, li-jin-gou approved these changes

2023-12-22 04:59 UTC, merged