docs: optimize protocol module documentation
cloudwego/cloudwego.github.io pull request #918
Opened 2024-01-06 10:33 UTC by ahaostudy

#### What type of PR is this?

docs

#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en:
zh(optional): 

#### (Optional) Which issue(s) this PR fixes:

2024-01-06 13:36 UTC, AsterDY commented on content/zh/docs/kitex/Tutorials/protocol/serialization-protocol/protobuf.md
> +### gRPC 协议
这里名字有点让人困惑，建议改为“使用gRPC作为传输协议“。然后下文先说明默认传输协议为Kitex-protobuf

2024-01-06 14:12 UTC, ahaostudy commented on content/zh/docs/kitex/Tutorials/protocol/serialization-protocol/protobuf.md
> +### gRPC 协议
Done

2024-01-06 14:30 UTC, cqqqq777 requested changes

2024-01-06 14:30 UTC, cqqqq777 commented on content/zh/docs/kitex/Tutorials/protocol/serialization-protocol/binary.md
> +Kitex 针对 Binary 协议编解码进行了优化，具体优化细节参考 “Reference - 高性能 Thrift 编解码 " 篇章，假如想要关闭这些优化，生成代码时可以加上 `-no-fast-api` 参数。
“Reference - 高性能 Thrift 编解码” 这个是在哪我没找到，感觉可以加个超链接

2024-01-06 14:41 UTC, ahaostudy commented on content/zh/docs/kitex/Tutorials/protocol/serialization-protocol/binary.md
> +Kitex 针对 Binary 协议编解码进行了优化，具体优化细节参考 “Reference - 高性能 Thrift 编解码 " 篇章，假如想要关闭这些优化，生成代码时可以加上 `-no-fast-api` 参数。
旧文档里面就有的，我找找看看

2024-01-06 15:02 UTC, ahaostudy commented on content/zh/docs/kitex/Tutorials/protocol/serialization-protocol/binary.md
> +Kitex 针对 Binary 协议编解码进行了优化，具体优化细节参考 “Reference - 高性能 Thrift 编解码 " 篇章，假如想要关闭这些优化，生成代码时可以加上 `-no-fast-api` 参数。
我也没找到这个，之前的提交里面也没有加上这个链接

2024-02-19 07:36 UTC, AsterDY approved these changes

2024-02-19 07:36 UTC, merged